### ISSUE TITLE
ProtoProxy - SyntaxError

### ISSUE THREAD

**Issue by s7xxrs** [SDOT-real/ExecutorDFiles#2]
![Screenshot 2024-12-27 222040](https://github.com/user-attachments/assets/07f41790-81c8-48c1-9e7d-15426c20913d)

**Comment by SDOT-real** [comment]
Most likely, this problem occurs due to improper installation. Be sure to name the file “executor.d.luau” and add it to the Luau-LSP definition file setting.
If this problem persists, a screenshot of your workspace and a screenshot of your .vscode settings would help me to assist you.

**Comment by s7xxrs** [comment]
It was my mistake, I changed the name to definitionFiles.luau, I reverted it and it no longer throws any error, sorry for the inconvenience.

By the way, thank you very much for this, it has been very helpful to me when making scripts, have a great week and end of the year 😸
